# this kustomization file is to publish the web only assets
resources:
  - posgres/posgres.yaml
  - willow.yaml
configMapGenerator:
  - name: postgres-config
    literals:
      - POSTGRES_DB=postgresdb
      - POSTGRES_USER=postgresadmin
      - POSTGRES_PASSWORD=admin123
  - name: postgreinit
    files:
      - posgres/initdb.sql
  - name: willow-config
    literals:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=postgresadmin
      - DATABASE_PASSWORD=admin123
      - DATABASE_USE_SSL=false
      - DATABASE_NAME=postgresdb