apiVersion: apps/v1
kind: Deployment
metadata:
  name: willow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: willow
  template:
    metadata:
      labels:
        app: willow
    spec:
      containers:
        - name: willow
          image: willow/schema
          command:
            - sh
            - -c
            - 'sleep 30 && npm run willow-generate && npm run sync-db && npm run willow-start'
          envFrom:
            - configMapRef:
                name: willow-config
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: willow
  labels:
    app: willow
spec:
  type: NodePort
  ports:
    - port: 3000
  selector:
    app: willow